First and second home task
steamstpre/Minko_Danylo_pmi_13 pull request #3
Opened 2021-09-21 16:29 UTC by steamstpre

2021-09-22 19:11 UTC, tetianastoyko requested changes

2021-09-22 19:11 UTC, tetianastoyko commented on practica/first_practica/prectica/main.py
> +while n+k <= 4 or n+k >= 18:
аналогічні коментарі

2021-09-22 19:11 UTC, tetianastoyko commented on practica/second_practica/main.py
> +        if res == 1:
Багато дублікату

2021-09-28 22:22 UTC, steamstpre reviewed
Home_task #3

2021-09-28 22:25 UTC, merged